### ISSUE TITLE
Resolve symlinks

### ISSUE THREAD

**Issue by yordis** [sindresorhus/resolve-cwd#1]
Related to this issue: https://github.com/facebook/create-react-app/issues/637

This is what they did 

```
// Make sure any symlinks in the project folder are resolved:
// https://github.com/facebook/create-react-app/issues/637
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);
```

So maybe a second param with a config key called `resolveSymlink`

```js
resolveCwd('something', { resolveSymlink: true } )
```

**Comment by kevva** [comment]
It should be supported already, see https://github.com/sindresorhus/resolve-from/blob/master/index.js#L16.

**Comment by yordis** [comment]
"Kids, sleep before you open an issue" ....
